Nama = input("Masukkan nama Anda: ")
NIM = int (input("Masukkan NIM Anda: "))
Paralel = int(input("Masukkan paralel Anda: "))
TTL = input("Masukkan tempat tanggal lahir Anda: ")
Alamat = input("Masukkan alamat Anda: ")
Hobby = input("Masukkan hobi Anda: ")
Nomor_HP = int(input("Masukkan nomor HP Anda: "))

print("Nama                     : ", Nama)
print("NIM                      : ", NIM)
print("Paralel                  : ", Paralel)
print("Tempat/Tanggal Lahir     : ", TTL)
print("Alamat                   : ", Alamat)
print("Hobby                    : ", Hobby)
print("No HP                    : ", Nomor_HP)