name = input("Masukkan nama Anda: ")
nim = int(input("Masukkan NIM Anda: "))
paralel = int(input("Masukkan paralel Anda: "))
ttl = input("Masukkan tempat tanggal lahir Anda: ")
address = input("Masukkan alamat Anda: ")
hobby = input("Masukkan hobi Anda: ")
phone_number = int(input("Masukkan nomor HP Anda: "))

print("\n                         ")
print("Nama                     : ", name)
print("NIM                      : ", nim)
print("Paralel                  : ", paralel)
print("Tempat/Tanggal Lahir     : ", ttl)
print("Alamat                   : ", address)
print("Hobby                    : ", hobby)
print("No HP                    : ", phone_number)